-- MySQL Script generated by MySQL Workbench
-- Sun Jan  8 19:49:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema train_schedule
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `train_schedule` ;

-- -----------------------------------------------------
-- Schema train_schedule
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `train_schedule` DEFAULT CHARACTER SET utf8 ;
USE `train_schedule` ;

-- -----------------------------------------------------
-- Table `train_schedule`.`Route`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `train_schedule`.`Route` ;

CREATE TABLE IF NOT EXISTS `train_schedule`.`Route` (
  `id_route` INT NOT NULL AUTO_INCREMENT,
  `name_route` VARCHAR(75) NULL,
  PRIMARY KEY (`id_route`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_schedule`.`Train`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `train_schedule`.`Train` ;

CREATE TABLE IF NOT EXISTS `train_schedule`.`Train` (
  `id_train` INT NOT NULL AUTO_INCREMENT,
  `name_train` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_train`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_schedule`.`Station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `train_schedule`.`Station` ;

CREATE TABLE IF NOT EXISTS `train_schedule`.`Station` (
  `id_station` INT NOT NULL AUTO_INCREMENT,
  `name_station` VARCHAR(45) NULL,
  PRIMARY KEY (`id_station`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_schedule`.`Track`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `train_schedule`.`Track` ;

CREATE TABLE IF NOT EXISTS `train_schedule`.`Track` (
  `id_track` INT NOT NULL AUTO_INCREMENT,
  `track_status` VARCHAR(45) NOT NULL,
  `track_number` INT NOT NULL,
  `Station_id_station` INT NOT NULL,
  PRIMARY KEY (`id_track`),
  INDEX `fk_Track_Station1_idx` (`Station_id_station` ASC) VISIBLE,
  CONSTRAINT `fk_Track_Station1`
    FOREIGN KEY (`Station_id_station`)
    REFERENCES `train_schedule`.`Station` (`id_station`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_schedule`.`Schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `train_schedule`.`Schedule` ;

CREATE TABLE IF NOT EXISTS `train_schedule`.`Schedule` (
  `id_schedule` INT NOT NULL AUTO_INCREMENT,
  `arrival` DATETIME(6) NOT NULL,
  `departure` DATETIME(6) NOT NULL,
  `Train_id_train` INT NOT NULL,
  `Station_id_station` INT NOT NULL,
  `Route_id_route` INT NOT NULL,
  PRIMARY KEY (`id_schedule`),
  INDEX `fk_Schedule_Train1_idx` (`Train_id_train` ASC) VISIBLE,
  INDEX `fk_Schedule_Station1_idx` (`Station_id_station` ASC) VISIBLE,
  INDEX `fk_Schedule_Route1_idx` (`Route_id_route` ASC) VISIBLE,
  CONSTRAINT `fk_Schedule_Train1`
    FOREIGN KEY (`Train_id_train`)
    REFERENCES `train_schedule`.`Train` (`id_train`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Schedule_Station1`
    FOREIGN KEY (`Station_id_station`)
    REFERENCES `train_schedule`.`Station` (`id_station`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Schedule_Route1`
    FOREIGN KEY (`Route_id_route`)
    REFERENCES `train_schedule`.`Route` (`id_route`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_schedule`.`Train_has_Route`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `train_schedule`.`Train_has_Route` ;

CREATE TABLE IF NOT EXISTS `train_schedule`.`Train_has_Route` (
  `Train_id_train` INT NOT NULL,
  `Route_id_route` INT NOT NULL,
  PRIMARY KEY (`Train_id_train`, `Route_id_route`),
  INDEX `fk_Train_has_Route_Route1_idx` (`Route_id_route` ASC) VISIBLE,
  INDEX `fk_Train_has_Route_Train1_idx` (`Train_id_train` ASC) VISIBLE,
  CONSTRAINT `fk_Train_has_Route_Train1`
    FOREIGN KEY (`Train_id_train`)
    REFERENCES `train_schedule`.`Train` (`id_train`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Train_has_Route_Route1`
    FOREIGN KEY (`Route_id_route`)
    REFERENCES `train_schedule`.`Route` (`id_route`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `train_schedule`.`Route_has_Station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `train_schedule`.`Route_has_Station` ;

CREATE TABLE IF NOT EXISTS `train_schedule`.`Route_has_Station` (
  `Route_id_route` INT NOT NULL,
  `Station_id_station` INT NOT NULL,
  PRIMARY KEY (`Route_id_route`, `Station_id_station`),
  INDEX `fk_Route_has_Station_Station1_idx` (`Station_id_station` ASC) VISIBLE,
  INDEX `fk_Route_has_Station_Route1_idx` (`Route_id_route` ASC) VISIBLE,
  CONSTRAINT `fk_Route_has_Station_Route1`
    FOREIGN KEY (`Route_id_route`)
    REFERENCES `train_schedule`.`Route` (`id_route`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Route_has_Station_Station1`
    FOREIGN KEY (`Station_id_station`)
    REFERENCES `train_schedule`.`Station` (`id_station`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
